#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExReport.DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataReport")]
	public partial class DataReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataReportDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataReportConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STCOKBC")]
		public ISingleResult<STCOKBCResult> STCOKBC()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<STCOKBCResult>)(result.ReturnValue));
		}
	}
	
	public partial class STCOKBCResult
	{
		
		private string _whcode;
		
		private string _ABBNAME;
		
		private string _whname;
		
		private string _dd;
		
		private string _MPCODE;
		
		private string _FULLNAME;
		
		private System.Nullable<decimal> _qty;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<decimal> _amt;
		
		public STCOKBCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whcode", DbType="VarChar(20)")]
		public string whcode
		{
			get
			{
				return this._whcode;
			}
			set
			{
				if ((this._whcode != value))
				{
					this._whcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNAME", DbType="VarChar(20)")]
		public string ABBNAME
		{
			get
			{
				return this._ABBNAME;
			}
			set
			{
				if ((this._ABBNAME != value))
				{
					this._ABBNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whname", DbType="VarChar(100)")]
		public string whname
		{
			get
			{
				return this._whname;
			}
			set
			{
				if ((this._whname != value))
				{
					this._whname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dd", DbType="VarChar(10)")]
		public string dd
		{
			get
			{
				return this._dd;
			}
			set
			{
				if ((this._dd != value))
				{
					this._dd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPCODE", DbType="VarChar(15)")]
		public string MPCODE
		{
			get
			{
				return this._MPCODE;
			}
			set
			{
				if ((this._MPCODE != value))
				{
					this._MPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(60)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this._qty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amt", DbType="Decimal(31,4)")]
		public System.Nullable<decimal> amt
		{
			get
			{
				return this._amt;
			}
			set
			{
				if ((this._amt != value))
				{
					this._amt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
